# SharePoint Configuration - FILL IN YOUR VALUES
# This file contains sensitive information - DO NOT commit to source control

[sharepoint]
client_id = "a66eeeec-2163-4bc6-9c69-03bd1141495b"
site_url = "https://payrocllc.sharepoint.com/sites/Roc_UCentral/Training%20Catalogue%20Please%20dont%20edit/Forms/AllItems.aspx?npsAction=createList"
library_name = "Payroc L&OD Library"
root_folder_path = "Training Catalogue (Please don't edit)"
